spring:
  application:
    name: 'tenant'
  datasource:
    url: jdbc:postgresql://localhost:5432/masterschemadb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org:
      springframework:
        security=DEBUG:

